Feat/fe/jeongchanyeong/nav
codestates-seb/seb44_main_019 pull request #72
Opened 2023-07-09 11:48 UTC by Jeongchanyeong

width 값을 % -> px로 변경하였습니다.

2023-07-09 13:11 UTC, DongwooJoo commented on client/src/component/nav/Nav.styled.ts
> +  height: 100vh;
8,9번째 라인에서 width, height 둘다 100%으로 주고,
상위 css인 App.css에서 nav, main에 16%, 84%퍼센트를 줘서 레이아웃하는 거 어떤가요?

*추후에 모바일 크기로 줄어들었을 때, Nav가 작아지게 하거나, 햄버거 버튼으로 들어가게 하는 거 논의해보시죠!

2023-07-10 00:52 UTC, lhs9602 requested changes

2023-07-10 00:52 UTC, lhs9602 commented on client/src/component/nav/Nav.styled.ts
>    flex-direction: flex-end;
flex-direction: flex-end 가 아니라 row여야 되지 않아요? 그리고 padding-left는 위치 조정을 위해서 임의로 넣으신거 같은데, LogoutButton을 감싸는 컴포넌트를 하나 만들고, 거기에 flex를 주고, justify-content를 flex-end로 하시면 될 것입니다

2023-07-10 00:52 UTC, lhs9602 commented on client/src/component/nav/Nav.styled.ts
> +  margin: 20px 0px 280px 0px;
여기도 위치 조정을 위해 넣으신 것 같은데, 로고를 포함한 로그아웃을 제외한 위쪽의 모든 요소를 하나의 div로 묶고, space-between하시면 정렬됩니다

2023-07-10 07:47 UTC, merged